### ISSUE TITLE
[ERROR] class file for com.microsoft.graph.httpcore.IAuthenticationProvider not found

### ISSUE THREAD

**Issue by demonsked** [microsoftgraph/msgraph-sdk-java-auth#17]
Please update maven snapshot. There is an issue. Instead of fixed microsoft-graph-auth-0.1.0-SNAPSHOT.jar maven downloads affected microsoft-graph-auth-0.1.0-20190227.065917-1.jar.

**Comment by jski-root** [comment]
would this cause the following issue?

The type com.microsoft.graph.httpcore.IAuthenticationProvider cannot be resolved. It is indirectly referenced from required .class filesJava(16777540)

**Comment by cheryalabalram** [comment]
While I am creating an object for IGraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider( authprovider ).buildClient();

giving compile time exception like : 
The type com.microsoft.graph.httpcore.IAuthenticationProvider cannot be resolved. It is indirectly referenced from required .class files

**Comment by einue** [comment]
I have the same error, hope this will be fixed soon.

I checked the com.microsoft.graph.httpcore - package. There is only the class named 	ICoreAuthenticationProvider instead of  IAuthenticationProvider . this was changed for 8 month.

Can anybody fix this soon? The Maven dependency on https://oss.sonatype.org/#nexus-search;quick~microsoft-graph-auth should be updated.

**Comment by debarshri** [comment]
see #12

**Comment by MIchaelMainer** [comment]
This is available in microsoft-graph-auth 0.2.0-SNAPSHOT.
