### ISSUE TITLE
Logging instead of Exception.printStackTrace()

### ISSUE THREAD

**Issue by Aelentel** [microsoftgraph/msgraph-sdk-java-auth#66]
use a Logging facade instead of using Exception.printStackTrace() be it SLF4J or any useable facade.

to be honest this is a pain for any logging aggregator pipeline in production systems.

where : com.microsoft.graph.auth.publicClient.UsernamePasswordProvider 
[AB#7988](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7988)

**Comment by baywet** [comment]
@Aelentel Thanks for reaching out.
At this moment we're not actively investing on this authentication library anymore. Our [v3 work](https://github.com/Azure/azure-sdk-for-java/wiki/Logging-with-Azure-SDK) includes replacing this library by azure-identity instead.
Azure-identity already uses sl4j and you can [tweak the logs through configuration](https://github.com/Azure/azure-sdk-for-java/wiki/Logging-with-Azure-SDK).
Can I suggest you try the preview of the v3? Not only you'll benefits the other improvements this newer version provides, but some of the logging issues you reported have been fixed too.
Closing

**Comment by Aelentel** [comment]
@baywet thanks for the answer, but fact is that i'm absolutely not using Azure services, I'm using Graph API to make booking of Teams conferences.
so basically it's Graph SDK + Graph Auth.

after looking at the Azure SDK i'm not sure how to mix those 2 things together.

in any cases, thanks for the answer.

**Comment by baywet** [comment]
Sorry for the previous post it seems I pasted twice the same link instead of a link to this issue https://github.com/microsoftgraph/msgraph-sdk-java/issues/628

More importantly in the upgrade guide you'll find a link to authentication samples. https://github.com/microsoftgraph/msgraph-sdk-java/blob/feature/v3/docs/upgrade-to-v3-auth.md

There you'll find sample code for the different authentication scenario.
You don't need any azure service to use the azure identity library, besides the Microsoft identity platform of course.

**Comment by Aelentel** [comment]
@baywet Thanks a lot, that indeed helps quite a lot.
I'll update the dependencies, code, the example provided are really helpful !
